### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Flonja** [Pikachu920/WebAddon#1]
Is there a compiled version of this addon or do I need to compile it myself, if so, how?

**Comment by abandonedaccount6235** [comment]
it is not quite ready yet, it should be ready for release in about a week

**Comment by Flonja** [comment]
Ok, thanks for the answer

**Comment by abandonedaccount6235** [comment]
i will make an example script then release

**Comment by abandonedaccount6235** [comment]
release is going to take longer than expected...

**Comment by abandonedaccount6235** [comment]
I have released a snapshot version... know that there was a bug that could crash your server when reloading the script without any stacktrace but I *think* I have fixed it. If you get the bug, please open an issue here -- maybe it will print a stacktrace for you.
