### ISSUE TITLE
Can't parse url correctly

### ISSUE THREAD

**Issue by Olyno** [Pikachu920/WebAddon#3]
**Description of the problem:**

Url is not parsing good.

**Proof:**

This works fine:
```vb
open a web server on port 8080:
	get /%{_arg}%:
		if {_arg} is "test.html":
			send back file contents of "{@test_path}/%{_arg}%"
		send back "ARG= %{_arg}%"
```
but this doesn't work:
```vb
open a web server on port 8080:
	get /%{_arg}%.html:
		if {_arg} is "test":
			send back file contents of "{@test_path}/%{_arg}%"
		send back "ARG= %{_arg}%"
```
None will be return

**Idea to correct the problem:**

Just accept extensions of files as text.

**Minecraft server version:** git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2)
**Skript version:** 2.2 dev37c
**Webaddon version:** 1.1

**Comment by abandonedaccount6235** [comment]
what did you try to navigate to

**Comment by Olyno** [comment]
I just tried to get only the name of the file without the extension

**Comment by abandonedaccount6235** [comment]
That's the issue. you didn't request something ending in .html
