### ISSUE TITLE
SSL please?

### ISSUE THREAD

**Issue by kierandrewett** [Pikachu920/WebAddon#7]
Look, I'm fed up. There is legit no way to make requests using my API with JS for example, because or CORS. Is there any chance you could update webaddon to support SSL or something with like ports other than 80 and 443.

_Also, Pika if you are reading this: I'm pretty sure it's possible [http://sparkjava.com/documentation#embedded-web-server](http://sparkjava.com/documentation#embedded-web-server)_

Thanks, Ender

**Comment by kierandrewett** [comment]
https://github.com/tipsy/spark-ssl

**Comment by kierandrewett** [comment]
Great still no response, idk what I'm gunna do anymore, i've however set up a reverse prorxy hopefully this is the result.

**Comment by ember-ana** [comment]
reverse proxy with nginx works but why not just give the man his SSL 😩

**Comment by kierandrewett** [comment]
i agree
